title: Kevin Slote # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Kevin Slote is a Principal Data Scientist at and works as a researcher in A.I. Kevin does applied math and neuroscience research as a Ph.D. candidate in the <a href="https://math.gsu.edu/ibelykh/belykh_lab.html">Biological and Engineering Networks Lab</a>. He works on predicting epilepsy based on networks of interacting neurons and uses similar techniques in cyber security. Kevin has a professional history doing machine learning in e-discovery and lives in Atlanta, Ga.
  <br><br>
  
  <br><br>
  <a href="www.linkedin.com/in/kevin-slote">LinkedIn Profile</a> </br>
  <a href="https://math.stackexchange.com/users/95560/kslote1">Mathoverflow Profile</a> </br>
  <a href="mailto: kslote1@gmail.com">Send Email</a>


  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
