title: Kevin Slote # your name (or website title) here
logo: "/images/me2.jpg?raw=true" # your photo (or logo) here
description:
   Kevin Slote is a practicing Data Scientist with a keen interest in artificial intelligence research and its practical applications.
   Holding a Master's degree in abstract algebra, Kevin has developed a passion for category theory and topological data analysis.
   Currently pursuing his Ph.D. in the <a href="https://math.gsu.edu/ibelykh/belykh_lab.html">Biological and Engineering Networks Lab</a>,
   he strives to deepen his understanding of applied mathematics and neuroscience.
   His research explores the prediction of epilepsy through the examination of complex neuronal networks,
   and he also applies these techniques to cybersecurity.

  With a background in machine learning within the field of e-discovery, Kevin remains committed to learning and refining 
  his skills in both theoretical and applied domains. Residing in Atlanta, Georgia, he continually seeks opportunities to 
  contribute to the scientific community and grow both personally and professionally within the realms of data science and artificial intelligence.
  <br><br>
  
  <br><br>
  <a href="www.linkedin.com/in/kevin-slote">LinkedIn Profile</a> </br>
  <a href="https://math.stackexchange.com/users/95560/kslote1">Mathoverflow Profile</a></br>
  <a href="https://sites.google.com/view/kevin-slote">Academic Professional Website</a></br>
  <a href="https://twitter.com/kslote1">Twitter</a></br>
  <a href="https://medium.com/@kslote1">Medium</a></br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
