title: Kevin Slote # your name (or website title) here
logo: "/images/me2.jpg?raw=true" # your photo (or logo) here
description:
   Applied Math: Finishing Ph.D. dissertation.
   Pure Math: Algebraic Geometry maters degree/
   Data Science: Principal Data Scientist in the corporate grind.
   Gernative AI: Transformers, LLMs.
   Math: computational topology, dynamical systems, causal models.
  <br><br>
  
  <br><br>
  <a href="www.linkedin.com/in/kevin-slote">LinkedIn Profile</a> </br>
  <a href="https://math.stackexchange.com/users/95560/kslote1">Mathoverflow Profile</a></br>
  <a href="https://sites.google.com/view/kevin-slote">Academic Professional Website</a></br>
  <a href="https://twitter.com/kslote1">Twitter</a></br>
  <a href="https://medium.com/@kslote1">Medium</a></br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
